services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile-frontend
    volumes:
      - frontend-dist:/home/node/app/frontend/dist/frontend/browser

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile-backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend-db

  backend-db:
    container_name: backend-db
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DATABASE_DATABASE}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - backend-db-data:/var/lib/postgresql/data

  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: Dockerfile-webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend-dist:/usr/share/nginx/html:ro
      - ./webserver/logs:/var/log/nginx
      - ./webserver/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  frontend-dist:
  backend-db-data:
    driver: local
