FROM nginx:alpine

COPY ./webserver/conf.d /etc/nginx/conf.d
RUN apk add --no-cache certbot certbot-nginx
VOLUME /etc/letsencrypt
CMD nginx && certbot \
    --nginx \
    --email "$CERTBOT_EMAIL" --agree-tos --no-eff-email \
    -d "$CERTBOT_DOMAIN" \
    --keep --expand \
    && nginx -s quit \
    && nginx -g "daemon off;"
