services:
  backend-db:
    container_name: ${CONTAINER_NAME_DB}
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DATABASE_DATABASE}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
